github:
  description: "RocketMQ APIs - Protobuf definition for Apache RocketMQ"
  features:
    # Enable wiki for documentation
    wiki: true
    # Enable issue management
    issues: true
    # Enable projects for project management boards
    projects: true
  protected_branches:
    main: {}
notifications:
  commits:      commits@rocketmq.apache.org
  issues:       commits@rocketmq.apache.org
  pullrequests: commits@rocketmq.apache.org
  jobs:         commits@rocketmq.apache.org
  discussions:  dev@rocketmq.apache.org
